# Generated by Django 5.2.4 on 2025-07-09 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='pokemontype',
            constraint=models.UniqueConstraint(fields=('pokemon', 'type_group'), name='unique_pokemon_type'),
        ),
        migrations.AddConstraint(
            model_name='usertype',
            constraint=models.UniqueConstraint(fields=('user', 'type_group'), name='unique_user_type_group'),
        ),
    ]
